version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout      
      - restore_cache:
          key: build-cache-{{ checksum "package.json" }}
      - run: rm -rf node_modules
      - run: npm install
      - run: npm test
      - save_cache:
          key: build-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  build:
    jobs:
      - build